# Generated by Django 6.0.7 on 2026-07-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Médico')),
                ('specialty', models.CharField(max_length=255, verbose_name='Especialidade')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contato/Telefone')),
                ('crm', models.CharField(blank=True, max_length=50, null=True, verbose_name='CRM')),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='HospitalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título da Imagem')),
                ('image', models.ImageField(upload_to='hospital/', verbose_name='Imagem')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Imagem do Hospital',
                'verbose_name_plural': 'Imagens do Hospital',
            },
        ),
        migrations.CreateModel(
            name='HospitalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hospital Nossa Senhora do Brasil', max_length=255, verbose_name='Nome')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('pix_key', models.CharField(max_length=255, verbose_name='Chave PIX para Doações')),
                ('working_hours', models.CharField(default='Atendimento 24 horas', max_length=100, verbose_name='Horário de Atendimento')),
                ('about_title', models.CharField(default='Compromisso com a saúde e o bem-estar da comunidade.', max_length=255, verbose_name='Título Sobre')),
                ('about_text_1', models.TextField(verbose_name='Texto Sobre 1')),
                ('about_text_2', models.TextField(verbose_name='Texto Sobre 2')),
                ('mission', models.TextField(verbose_name='Missão')),
                ('vision', models.TextField(verbose_name='Visão')),
                ('values', models.TextField(verbose_name='Valores')),
            ],
            options={
                'verbose_name': 'Informações do Hospital',
                'verbose_name_plural': 'Informações do Hospital',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('text', models.TextField(verbose_name='Descrição')),
                ('icon', models.CharField(default='FaUserMd', max_length=100, verbose_name='Classe do Ícone (React Icons)')),
                ('category', models.CharField(choices=[('imagem', 'Exames de Imagem'), ('laboratorial', 'Exames Laboratoriais'), ('consulta', 'Consultas Médicas Especializadas'), ('medicamento', 'Administração de Medicamentos'), ('cirurgia', 'Cirurgias'), ('plantao', 'Plantão Médico 24 Horas'), ('geral', 'Geral')], default='geral', max_length=50, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
