# Generated by Django 6.0.7 on 2026-07-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título da Realização')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Imagem Ilustrativa')),
                ('data_realizacao', models.DateField(verbose_name='Data da Realização')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Realização / Projeto',
                'verbose_name_plural': 'Realizações e Projetos',
                'ordering': ['-data_realizacao'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Médico')),
                ('especialidade', models.CharField(max_length=100, verbose_name='Especialidade')),
                ('crm', models.CharField(max_length=20, unique=True, verbose_name='CRM')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Foto de Perfil')),
                ('biografia', models.TextField(verbose_name='Biografia')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo no Site?')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título da Campanha')),
                ('descricao', models.TextField(verbose_name='Descrição da Campanha')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='campaigns/', verbose_name='Imagem de Capa')),
                ('chave_pix', models.CharField(max_length=100, verbose_name='Chave Pix para Doação')),
                ('beneficiario', models.CharField(max_length=150, verbose_name='Beneficiário (Nome/Razão Social)')),
                ('ativa', models.BooleanField(default=True, verbose_name='Campanha Ativa?')),
            ],
            options={
                'verbose_name': 'Campanha de Doação',
                'verbose_name_plural': 'Campanhas de Doação',
            },
        ),
        migrations.CreateModel(
            name='DonationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo (Ex: Pix, Transferência)')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição (Ex: Chave CNPJ, Agência e Conta)')),
                ('instrucoes', models.TextField(verbose_name='Instruções de Doação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Forma de Doação Fixa',
                'verbose_name_plural': 'Formas de Doação Fixas',
            },
        ),
        migrations.CreateModel(
            name='HospitalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Hospital')),
                ('historia', models.TextField(verbose_name='História do Hospital')),
                ('missao', models.TextField(verbose_name='Missão')),
                ('visao', models.TextField(verbose_name='Visão')),
                ('valores', models.TextField(verbose_name='Valores')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram (Link ou User)')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook (Link ou User)')),
                ('horario_funcionamento', models.CharField(max_length=150, verbose_name='Horário de Funcionamento')),
            ],
            options={
                'verbose_name': 'Informação Institucional',
                'verbose_name_plural': 'Informações Institucionais',
            },
        ),
    ]
